/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reception2;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reception 2
 */
public class Imprsion_Facture extends javax.swing.JFrame {

    /**
     * Creates new form Imprsion
     */
    
    public String  id_cons1,  patient1,Nom1,  Post_nom1,  TG1,  CV1, SNP1,  SR1,date;
    private Statement state;
    private ResultSet result;
    public Imprsion_Facture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jour = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Num_Facture = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tab_Fac = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TG = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SNP = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CV = new javax.swing.JLabel();
        SR = new javax.swing.JLabel();
        Patient = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Note d'Honoraire");

        imprimer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/LOGO3.png"))); // NOI18N

        jour.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jour.setText("................");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("5 Bis, Avenue Mont des Arsts, C/ LINGWALA");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tel : (+243) 812902286/815203932");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E-mail: michelmusafiri@yahoo.fr");

        Num_Facture.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Num_Facture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Num_Facture.setText("...............................................................");

        titre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("FACTURE");

        Tab_Fac.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Tab_Fac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prestation", "Prix /$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_Fac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tab_Fac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_FacMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Tab_Fac);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel29.setText("Solde Net à payer:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel14.setText("Total Global : ");

        TG.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        TG.setText("........................");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel23.setText("$");

        SNP.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        SNP.setText("........................");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel30.setText("$");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel31.setText("Somme remboursée :");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel27.setText("Caution versée:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel28.setText("$");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel32.setText("$");

        CV.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        CV.setText("........................");

        SR.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        SR.setText("........................");

        Patient.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Patient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient.setText("Pacient");

        javax.swing.GroupLayout imprimerLayout = new javax.swing.GroupLayout(imprimer);
        imprimer.setLayout(imprimerLayout);
        imprimerLayout.setHorizontalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imprimerLayout.createSequentialGroup()
                                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SNP)
                                            .addComponent(TG)
                                            .addComponent(CV))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(imprimerLayout.createSequentialGroup()
                                        .addComponent(SR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel27)
                            .addComponent(jLabel14)))
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(titre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imprimerLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(imprimerLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5)))
                    .addComponent(Num_Facture, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imprimerLayout.setVerticalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_Facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TG)
                        .addComponent(jLabel23))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(CV)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(SNP)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(SR))
                .addGap(51, 51, 51)
                .addComponent(jour))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Print.png"))); // NOI18N
        jMenuItem2.setText("Imprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_usradd.png"))); // NOI18N
        jMenuItem3.setText("Nom Client");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Exit2.png"))); // NOI18N
        jMenuItem1.setText("Fermer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void info(String id_cons, String Nom, String Post_nom, String sexe, String age, String tg, String cv, String snp, String sr){
        Nom1=Nom;
        Post_nom1=Post_nom;
        patient1 =Nom1+"-"+Post_nom1;
        Num_Facture.setText("Facture N°: 00"+id_cons);
        Patient.setText("Patient : "+patient1);
        Date da=new Date();
        DateFormat dat= DateFormat.getDateInstance( DateFormat.FULL);
        date=dat.format(da);
        jour.setText("Fait à Kinshasa le "+date);
        TG.setText(tg);
        CV.setText(cv);
        SNP.setText(snp);
        SR.setText(sr);
         try {  
                 //affichage du Traitement
                state = (Statement) connection.getInstance().createStatement();
                 result = state.executeQuery("SELECT * FROM facture WHERE id_cons='"+id_cons+"';");
                           DefaultTableModel Table4=  (DefaultTableModel) Tab_Fac.getModel();
                           Table4.setColumnCount(0);
                           Table4.addColumn("préstation");
                           Table4.addColumn("Prix Total/$");
                           Table4.setRowCount(0);
                           while (result.next())
                              {//
                                    Object[] objets= new Object[2];
                                    objets[0]= result.getString("prestation");
                                    objets[1]= result.getString("prix");
                                    Table4.addRow(objets);
                              }

                           //Centrer les elment d'un colonne
                           DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                           centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                           Tab_Fac.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
                } catch (SQLException ex) {
                    Logger.getLogger(Sv.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }
    private void Tab_FacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_FacMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab_FacMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MPanelPrinter p=new MPanelPrinter(imprimer,1);
        p.setLRMargins(100);
        p.setTBMargins(90);
        p.print();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       patient1= nom+"-"+post_nom;
       Patient.setText("Patient : "+patient1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       patient1= nom+"-"+post_nom;
       Patient.setText("Patient : "+patient1);
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imprsion_Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imprsion_Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imprsion_Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imprsion_Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imprsion_Facture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CV;
    private javax.swing.JLabel Num_Facture;
    private javax.swing.JLabel Patient;
    private javax.swing.JLabel SNP;
    private javax.swing.JLabel SR;
    private javax.swing.JLabel TG;
    private javax.swing.JTable Tab_Fac;
    private javax.swing.JPanel imprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel jour;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
