/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reception2;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reception 2
 */
public class Imprsion_tARIFICATION extends javax.swing.JFrame {

    /**
     * Creates new form Imprsion
     */
    
    public String  id_cons1,  patient1,Nom1,  Post_nom1,  TG1,  CV1, SNP1,  SR1,date;
    private Statement state;
    private ResultSet result;
    protected Tarification tarification= new Tarification ();
    public Imprsion_tARIFICATION() {
        initComponents();
         try {
            state = (Statement) connection.getInstance().createStatement();
            result = state.executeQuery("SELECT* FROM  examen ORDER BY Examen;");
            DefaultTableModel Table=  (DefaultTableModel) Tab_PRIX.getModel();
            String no;
            Table.setColumnCount(0);

            Table.addColumn("Examen");
            Table.addColumn("Type");
            Table.addColumn("Prix/USD");
            Table.setRowCount(0);
            while (result.next())
            {//
                /*no=result.getString("Nom");
                System.out.println(no);*/
                Object[] objets= new Object[3];
                objets[0]= result.getString("Examen");
                objets[1]= result.getString("Type");
                objets[2]= result.getString("Prix");
                Table.addRow(objets);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tarification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimer = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tab_PRIX = new javax.swing.JTable();
        Id_User = new javax.swing.JLabel();
        User_nam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Note d'Honoraire");

        imprimer.setBackground(new java.awt.Color(255, 255, 255));

        titre.setFont(new java.awt.Font("Times New Roman", 1, 14));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("TARIFICATION");

        Tab_PRIX.setFont(new java.awt.Font("Times New Roman", 0, 11));
        Tab_PRIX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomination", "Type", "Prix /$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_PRIX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tab_PRIX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_PRIXMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Tab_PRIX);

        Id_User.setText("Id_user");

        User_nam.setText("user");

        javax.swing.GroupLayout imprimerLayout = new javax.swing.GroupLayout(imprimer);
        imprimer.setLayout(imprimerLayout);
        imprimerLayout.setHorizontalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Id_User)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(User_nam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imprimerLayout.setVerticalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_User)
                    .addComponent(User_nam))
                .addGap(11, 11, 11))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Print.png"))); // NOI18N
        jMenuItem2.setText("Imprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Undo.png"))); // NOI18N
        jMenuItem1.setText("Retour");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void user(String id_user, String User)
        {
            User_nam.setText(User);
            Id_User.setText(id_user);
        }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MPanelPrinter p=new MPanelPrinter(imprimer,1);
        p.setLRMargins(100);
        p.setTBMargins(90);
        p.print();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
    int H=tailleEcran.height;
    int L=tailleEcran.width;
    tarification.setSize(L, H);//Longeure et Hauteur l'ecran
    tarification.setLocationRelativeTo(null);//Permet de centrer le JFrame
    tarification.setVisible(true);
    tarification.user(Id_User.getText(), User_nam.getText());// Utilisateur
    this.setVisible(false);
          
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       patient1= nom+"-"+post_nom;
    }//GEN-LAST:event_jMenu1ActionPerformed

private void Tab_PRIXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_PRIXMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_Tab_PRIXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imprsion_tARIFICATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imprsion_tARIFICATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imprsion_tARIFICATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imprsion_tARIFICATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imprsion_tARIFICATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id_User;
    private javax.swing.JTable Tab_PRIX;
    private javax.swing.JLabel User_nam;
    private javax.swing.JPanel imprimer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
