/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reception2;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reception 2
 */
public class Imprsion extends javax.swing.JFrame {

    /**
     * Creates new form Imprsion
     */
    
    public String  id_cons1, patient1, Nom1,  Post_nom1,  TG1,  CV1, SNP1,  SR1,date;
    private Statement state;
    private ResultSet result;
    public Imprsion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jour = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Patient_identite = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TG2 = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tab_Ho = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TG = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SNP = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CV = new javax.swing.JLabel();
        SR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Note d'Honoraire");

        imprimer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/LOGO3.png"))); // NOI18N

        jour.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jour.setText("................");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("5 Bis, Avenue Mont des Arsts, C/ LINGWALA");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tel : (+243) 812902286/815203932");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E-mail: michelmusafiri@yahoo.fr");

        Patient_identite.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Patient_identite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Patient_identite.setText("...............................................................");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("et vous informe par la même occasion que le montant  des honoraires pour les soins médicaux  dont les détails  ");

        TG2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TG2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TG2.setText("OOOOOO");

        titre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("NOTE ");

        Tab_Ho.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Tab_Ho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Consultantion + Visites médicales ", null, null, "0"},
                {"Radiologie", null, null, "0"},
                {"ECG", null, null, "0"},
                {"Echographie", null, null, "0"},
                {"Echographie cardiaque", null, null, "0"},
                {"Gastroscopie", null, null, "0"},
                {"Rectoscopie", null, null, "0"},
                {"Kinésithérapie", null, null, "0"},
                {"Laboratoire", null, null, "0"},
                {"Actes médicaux", null, null, "0"},
                {"Actes chirurgicaux", null, null, "0"},
                {"Anesthésiste", null, null, "0"},
                {"accouchement", null, null, "0"},
                {"Médicament + Perfusion ", null, null, "0"},
                {"Actes infirmiers +soins", null, null, "0"},
                {"Occupation chambre", null, null, "0"},
                {"Frais administratifs", null, null, "0"},
                {null, null, null, "0"},
                {null, null, null, "0"},
                {null, null, null, "0"},
                {null, null, null, "0"},
                {null, null, null, "0"}
            },
            new String [] {
                "Prestation", "Quantité", "Prix Unitaire/$", "Prix Total/$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tab_Ho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tab_Ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_HoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Tab_Ho);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setText("Solde Net à payer:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Total Global : ");

        TG.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TG.setText("........................");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("$");

        SNP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SNP.setText("........................");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setText("$");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("Somme remboursée :");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText("Caution versée:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setText("$");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("$");

        CV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CV.setText("........................");

        SR.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SR.setText("........................");

        javax.swing.GroupLayout imprimerLayout = new javax.swing.GroupLayout(imprimer);
        imprimer.setLayout(imprimerLayout);
        imprimerLayout.setHorizontalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imprimerLayout.createSequentialGroup()
                                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SNP)
                                            .addComponent(TG)
                                            .addComponent(CV))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(imprimerLayout.createSequentialGroup()
                                        .addComponent(SR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel27)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)))
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Patient_identite, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(titre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imprimerLayout.createSequentialGroup()
                            .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TG2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imprimerLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(imprimerLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(5, 5, 5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imprimerLayout.setVerticalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Patient_identite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TG)
                        .addComponent(jLabel23))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(CV)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(SNP)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(SR))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimerLayout.createSequentialGroup()
                        .addComponent(jour)
                        .addGap(24, 24, 24))))
        );

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Print.png"))); // NOI18N
        jMenuItem2.setText("Imprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_usradd.png"))); // NOI18N
        jMenuItem4.setText("Nom Client");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Exit2.png"))); // NOI18N
        jMenuItem1.setText("Fermer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void info(String id_cons, String Nom, String Post_nom, String TG1, String CV1,String SNP1, String SR1){
        titre.setText("NOTE D'HONORAIRE");
        Nom1=Nom;
        Post_nom1=Post_nom;
        String patient =Nom1+"-"+Post_nom1;
        Patient_identite.setText("La direction de la clinique de l'Espoir présente ses compliments à Mr (Mm, Mll) "+patient);// Affectation patient
        Date da=new Date();
        DateFormat dat= DateFormat.getDateInstance( DateFormat.FULL);
        date=dat.format(da);
        jour.setText("Fait à Kinshasa le "+date);
        TG2.setText("figurent ci-dessous s'élève à  "+TG1+"$");
        TG.setText(TG1);
        CV.setText(CV1);
        SNP.setText(SNP1);
        SR.setText(SR1);
         try {  
                 //affichage du Traitement
                state = (Statement) connection.getInstance().createStatement();
                 result = state.executeQuery("SELECT * FROM honoraire WHERE id_cons='"+id_cons+"';");
                           DefaultTableModel Table4=  (DefaultTableModel) Tab_Ho.getModel();
                           Table4.setColumnCount(0);
                           Table4.addColumn("préstation");
                           Table4.addColumn("Quantité");
                           Table4.addColumn("Prix Unitaire/$");
                           Table4.addColumn("Prix Total/$");
                           Table4.setRowCount(0);
                           while (result.next())
                              {//
                                    Object[] objets= new Object[4];
                                    objets[0]= result.getString("prestation");
                                    objets[1]= result.getString("qte");
                                    objets[2]= result.getString("pu");
                                    objets[3]= result.getString("pt");
                                    Table4.addRow(objets);
                              }
                           //Centrer les elment d'un colonne
                           DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                           centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                           Tab_Ho.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
                           Tab_Ho.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
                           Tab_Ho.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );


                } catch (SQLException ex) {
                    Logger.getLogger(Sv.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }
    private void Tab_HoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_HoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab_HoMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MPanelPrinter p=new MPanelPrinter(imprimer,1);
        p.setLRMargins(100);
        p.setTBMargins(90);
        p.print();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
       patient1= nom+"-"+post_nom;
       Patient_identite.setText("La direction de la clinique de l'Espoir présente ses compliments à Mr (Mm, Mll) "+patient1);
      
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imprsion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imprsion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imprsion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imprsion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imprsion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CV;
    private javax.swing.JLabel Patient_identite;
    private javax.swing.JLabel SNP;
    private javax.swing.JLabel SR;
    private javax.swing.JLabel TG;
    private javax.swing.JLabel TG2;
    private javax.swing.JTable Tab_Ho;
    private javax.swing.JPanel imprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel jour;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
