/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Patient.java
 *
 * Created on 8 août 2018, 20:46:13
 */
package reception2;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samy-MBIYA
 */
public class Liste_Patient extends javax.swing.JFrame {

    /** Creates new form Liste_Patient */
    public Liste_Patient() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Rech_PN = new javax.swing.JTextField();
        Bt_rech = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rech_Conv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Rec_ID = new javax.swing.JTextField();
        Rec_nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        postnomLabel = new javax.swing.JLabel();
        postnomField = new javax.swing.JTextField();
        prenomField = new javax.swing.JTextField();
        prenomLabel = new javax.swing.JLabel();
        sexeLabel = new javax.swing.JLabel();
        sexeField = new javax.swing.JTextField();
        dnField = new javax.swing.JTextField();
        dnLabel = new javax.swing.JLabel();
        ecLabel = new javax.swing.JLabel();
        ecField = new javax.swing.JTextField();
        adresseField = new javax.swing.JTextField();
        adresseLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        professionField = new javax.swing.JTextField();
        professionLabel = new javax.swing.JLabel();
        employeurLabel = new javax.swing.JLabel();
        employeurField = new javax.swing.JTextField();
        ATDC_1 = new javax.swing.JTextField();
        employeurLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        User_nam = new javax.swing.JLabel();
        Id_User = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_liste = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTE DES PATIENT");
        setFocusTraversalPolicyProvider(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Recherche Patient"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14));

        Rech_PN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rech_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rech_PNActionPerformed(evt);
            }
        });

        Bt_rech.setFont(new java.awt.Font("Tahoma", 0, 14));
        Bt_rech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_search.png"))); // NOI18N
        Bt_rech.setText("Recherche ");
        Bt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rechActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Post-Nom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Convention");

        Rech_Conv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("ID");

        Rec_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rec_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rec_IDActionPerformed(evt);
            }
        });

        Rec_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rec_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rec_nomActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Nom");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rech_Conv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Rec_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rech_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rec_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addComponent(Bt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Rec_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Rec_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rech_PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Bt_rech))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rech_Conv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information du Patient"));

        nomLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        nomLabel.setText("Nom:");

        nomField.setFont(new java.awt.Font("Tahoma", 0, 14));

        postnomLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        postnomLabel.setText("Postnom:");

        postnomField.setFont(new java.awt.Font("Tahoma", 0, 14));
        postnomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postnomFieldActionPerformed(evt);
            }
        });

        prenomField.setFont(new java.awt.Font("Tahoma", 0, 14));

        prenomLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        prenomLabel.setText("Prenom:");

        sexeLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        sexeLabel.setText("Sexe:");

        sexeField.setFont(new java.awt.Font("Tahoma", 0, 14));

        dnField.setFont(new java.awt.Font("Tahoma", 0, 14));

        dnLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        dnLabel.setText("Né le:");

        ecLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        ecLabel.setText("Etat Civil:");

        ecField.setFont(new java.awt.Font("Tahoma", 0, 14));

        adresseField.setFont(new java.awt.Font("Tahoma", 0, 14));

        adresseLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        adresseLabel.setText("Adresse:");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        phoneLabel.setText("Phone:");

        phoneField.setFont(new java.awt.Font("Tahoma", 0, 14));

        professionField.setFont(new java.awt.Font("Tahoma", 0, 14));

        professionLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        professionLabel.setText("Profession:");

        employeurLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        employeurLabel.setText("Employeur:");

        employeurField.setFont(new java.awt.Font("Tahoma", 0, 14));

        ATDC_1.setFont(new java.awt.Font("Tahoma", 0, 14));

        employeurLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        employeurLabel1.setText("ATDC");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomLabel)
                    .addComponent(sexeLabel)
                    .addComponent(dnLabel)
                    .addComponent(ecLabel)
                    .addComponent(adresseLabel)
                    .addComponent(phoneLabel)
                    .addComponent(professionLabel)
                    .addComponent(employeurLabel)
                    .addComponent(postnomLabel)
                    .addComponent(nomLabel)
                    .addComponent(employeurLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ATDC_1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(postnomField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(sexeField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(dnField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(ecField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(adresseField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(professionField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(employeurField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(prenomField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(nomField, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomLabel))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postnomLabel)
                    .addComponent(postnomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexeLabel)
                    .addComponent(sexeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dnLabel)
                    .addComponent(dnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecLabel)
                    .addComponent(ecField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLabel)
                    .addComponent(adresseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professionLabel)
                    .addComponent(professionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeurLabel)
                    .addComponent(employeurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeurLabel1)
                    .addComponent(ATDC_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Save16.png"))); // NOI18N
        jButton3.setText("Enregitrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_edit.png"))); // NOI18N
        jButton4.setText("Modifier");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/DeleteHS.png"))); // NOI18N
        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Info.png"))); // NOI18N
        jButton2.setText("Signe viteaux");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setText("Infirmiere :");

        User_nam.setFont(new java.awt.Font("Tahoma", 3, 14));
        User_nam.setText("User");

        Id_User.setFont(new java.awt.Font("Tahoma", 3, 3));
        Id_User.setText("Id_User");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/paraJeu16.png"))); // NOI18N
        jButton6.setText("Tarification");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Id_User, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(User_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(User_nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Id_User))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tb_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Fiche", "Nom", "Postnom", "Prenom", "Sexe", "Date", "EC", "AD", "PH", "Pr", "Em"
            }
        ));
        Tb_liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_listeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_liste);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        jMenu5.setBackground(new java.awt.Color(255, 102, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Copy.png"))); // NOI18N
        jMenu5.setText(" Facture Proformat");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(255, 102, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/bottom.png"))); // NOI18N
        jMenu6.setText(" Facture hors cons");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(255, 102, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Preferences.png"))); // NOI18N
        jMenu7.setText(" Facture convention");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(255, 102, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Preferences.png"))); // NOI18N
        jMenu8.setText("Recherche ");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String id_p,nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em,ATDC,id_rech,Conv_Rech;
    private Statement state;
    private ResultSet result;
    public String user1,Id_pr1;
    protected Enregistrement enregistrement= new Enregistrement(); 
    protected Modification modification=new Modification();
    protected Suppression suppression=new Suppression();
    protected Sv sv=new Sv();
    protected Tarification tarification= new Tarification ();
    public void user(String Id_pr, String user)
    {
        Id_User.setText(Id_pr);
        User_nam.setText(user);
        
    }
private void postnomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postnomFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_postnomFieldActionPerformed

private void Rech_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rech_PNActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Rech_PNActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    affectation();
    if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{
    sv.info_patient(id_p, nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em,ATDC);
    Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
    int H=tailleEcran.height;
    int L=tailleEcran.width;
    sv.setSize(L, H);//Longeure et Hauteur l'ecran
    sv.setLocationRelativeTo(null);//Permet de centrer le JFrame
    sv.setVisible(true);
    sv.user(Id_User.getText(), User_nam.getText());
    this.setVisible(false);
   }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    affectation (); 
    if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{
         suppression.sup_patient(id_p);
        vide();
     }
    
    
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   affectation ();
    if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{
    try {
                modification.modif_Patien(id_p, nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em);
                vide();
        } catch (SQLException ex) {
            Logger.getLogger(Liste_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    affectation ();
    if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{
        try {
            enregistrement.enrg_patient(nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em);
            vide();
        } catch (SQLException ex) {
            Logger.getLogger(Liste_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
}//GEN-LAST:event_jButton3ActionPerformed

private void Bt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rechActionPerformed
// TODO add your handling code here:
    try {   
        state = (Statement) connection.getInstance().createStatement();
        id_rech=Rec_ID.getText();
        nom=Rec_nom.getText();
        postnom=Rech_PN.getText();
        Conv_Rech=Rech_Conv.getText();
         if ("".equals(id_rech)){
              result = state.executeQuery("SELECT* FROM  patient WHERE Nom LIKE '"+"%"+nom+"' OR Post_nom LIKE '"+"%"+postnom+"' ORDER BY id_pa DESC LIMIT 0,25;");
            }
         else{       
            result = state.executeQuery("SELECT* FROM  patient WHERE id_pa='"+id_rech+"' ;");
         }
          if (!"".equals(Conv_Rech)){
              result = state.executeQuery("SELECT* FROM  patient WHERE Employeur='"+Conv_Rech+"' ;");
          }
            DefaultTableModel Table=  (DefaultTableModel) Tb_liste.getModel();
            String no;
            Table.setColumnCount(0);
                   Table.addColumn("id_pa");
                   Table.addColumn("Nom");
                   Table.addColumn("Post_nom");
                   Table.addColumn("Prenom");
                   Table.addColumn("Sexe");
                   Table.addColumn("DN");
                   Table.addColumn("EC");
                   Table.addColumn("Adresse");
                   Table.addColumn("Phone");
                   Table.addColumn("Profession");
                   Table.addColumn("Employeur");
                   Table.addColumn("ATDC");
                   Table.setRowCount(0);
            while (result.next())
                      {//
                          /*no=result.getString("Nom");
                          System.out.println(no);*/
                            Object[] objets= new Object[12];
                            objets[0]= result.getString("id_pa");
                            objets[1]= result.getString("Nom");
                            objets[2]= result.getString("Post_nom");
                            objets[3]= result.getString("Prenom");
                            objets[4]= result.getString("Sexe");
                            objets[5]= result.getString("DN");
                            objets[6]= result.getString("EC");
                            objets[7]= result.getString("Adresse");
                            objets[8]= result.getString("Phone");
                            objets[9]= result.getString("Profession");
                            objets[10]= result.getString("Employeur");
                            objets[11]= result.getString("ATCD");
                            Table.addRow(objets);
                      }
        } catch (SQLException ex) {
            Logger.getLogger(Liste_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        // la vaveur du champ n'est pas null
        for(int i=0; i<Tb_liste.getRowCount(); i++) // compteur par rapport au tableau
        {   
            String nom_tri, pnom_tri;
            nom_tri=(String) Tb_liste.getModel().getValueAt(i, 1);// affecte la valeur de la celuile
            pnom_tri=(String)Tb_liste.getModel().getValueAt(i, 2);
            if( (nom == null ? nom_tri == null : nom.equals(nom_tri)) ||(postnom == null ? pnom_tri == null : postnom.equals(pnom_tri)) )
            {
                Tb_liste.changeSelection(i, 1, false, false);
                //System.out.println(nom_tri+"-"+pnom_tri);
            }else{
                
            }
        }    

}//GEN-LAST:event_Bt_rechActionPerformed
private void vide()
{
    nomField.setText("");
    postnomField.setText("");
    prenomField.setText("");
    sexeField.setText("");
    dnField.setText("");
    ecField.setText("");
    adresseField.setText("");
    phoneField.setText("");
    professionField.setText("");
    employeurField.setText("");
}
private void affectation ()
{
    nom=nomField.getText();
    postnom=postnomField.getText();
    prenom=prenomField.getText();
    sexe=sexeField.getText();
    dn=dnField.getText();
    ec=ecField.getText();
    ad=adresseField.getText();
    ph=phoneField.getText();
    pr=professionField.getText();
    em=employeurField.getText();
    ATDC=ATDC_1.getText();
}
private void Tb_listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_listeMouseClicked
// TODO add your handling code here:
   vide();
   int ligne_select= Tb_liste.getSelectedRowCount();//Nombre de lignes selectionner
   int in= Tb_liste.getSelectedRow();
   if(ligne_select==1)
   {
     id_p=(String)Tb_liste.getModel().getValueAt(in, 0);
     nomField.setText((String) Tb_liste.getModel().getValueAt(in, 1));
     postnomField.setText((String) Tb_liste.getModel().getValueAt(in, 2));
     prenomField.setText((String) Tb_liste.getModel().getValueAt(in, 3));
     sexeField.setText((String) Tb_liste.getModel().getValueAt(in, 4));
     dnField.setText((String) Tb_liste.getModel().getValueAt(in, 5));
     ecField.setText((String) Tb_liste.getModel().getValueAt(in, 6));
     adresseField.setText((String) Tb_liste.getModel().getValueAt(in, 7));
     phoneField.setText((String) Tb_liste.getModel().getValueAt(in, 8));
     professionField.setText((String) Tb_liste.getModel().getValueAt(in, 9));
     employeurField.setText((String) Tb_liste.getModel().getValueAt(in, 10));
     ATDC_1.setText((String) Tb_liste.getModel().getValueAt(in, 11));
   }
   
}//GEN-LAST:event_Tb_listeMouseClicked

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
    int H=tailleEcran.height;
    int L=tailleEcran.width;
    tarification.setSize(L, H);//Longeure et Hauteur l'ecran
    tarification.setLocationRelativeTo(null);//Permet de centrer le JFrame
    tarification.setVisible(true);
    tarification.user(Id_User.getText(), User_nam.getText());// Utilisateur
    this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jMenu7MouseClicked

private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jMenu6MouseClicked

private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
         Tarification T= new Tarification ();
        Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
        int H=tailleEcran.height;
        int L=tailleEcran.width;
        T.setSize(L, H);//Longeure et Hauteur l'ecran
        T.setLocationRelativeTo(null);//Permet de centrer le JFrame
        T.setVisible(true);
        T.user(Id_User.getText(),User_nam.getText());// envoi du pw et du user
        this.setVisible(false);
}//GEN-LAST:event_jMenu5MouseClicked

private void Rec_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rec_IDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Rec_IDActionPerformed

private void Rec_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rec_nomActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Rec_nomActionPerformed

private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jMenu8MouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Liste_Patient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATDC_1;
    private javax.swing.JButton Bt_rech;
    private javax.swing.JLabel Id_User;
    private javax.swing.JTextField Rec_ID;
    private javax.swing.JTextField Rec_nom;
    private javax.swing.JTextField Rech_Conv;
    private javax.swing.JTextField Rech_PN;
    private javax.swing.JTable Tb_liste;
    private javax.swing.JLabel User_nam;
    private javax.swing.JTextField adresseField;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JTextField dnField;
    private javax.swing.JLabel dnLabel;
    private javax.swing.JTextField ecField;
    private javax.swing.JLabel ecLabel;
    private javax.swing.JTextField employeurField;
    private javax.swing.JLabel employeurLabel;
    private javax.swing.JLabel employeurLabel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField postnomField;
    private javax.swing.JLabel postnomLabel;
    private javax.swing.JTextField prenomField;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField professionField;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JTextField sexeField;
    private javax.swing.JLabel sexeLabel;
    // End of variables declaration//GEN-END:variables
}
