/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medecin;

/**
 *
 * @author Reception 2
 */
public class Impression extends javax.swing.JFrame {

    
    /**
     * Creates new form Impression
     */
    public Impression() {
        initComponents();
    }

    public String Nom_Pat,Postnom_Pat,Prenom_Pat,Sexe_Pat, Use, Date_ne;
    public String s, ATCD, HMA, CA, EP, A, Date_cons;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        Patient = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titre1 = new javax.swing.JLabel();
        titre2 = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        Ne = new javax.swing.JLabel();
        Sexe_p = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SD = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        AT = new javax.swing.JTextPane();
        Patient1 = new javax.swing.JLabel();
        Patient2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        HiM = new javax.swing.JTextPane();
        Patient3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CMa = new javax.swing.JTextPane();
        Patient4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ExP = new javax.swing.JTextPane();
        Patient5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Diag = new javax.swing.JTextPane();
        Date_consul = new javax.swing.JLabel();
        Utilisateur = new javax.swing.JLabel();
        Patient8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imprimer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CLINIQUE DE L’ESPOIR");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone : (+243)812902286-815203932");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("www.clinique-de-l-espoir.org");

        titre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titre.setText("Patient :");

        Patient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Patient.setText("CONSULTATION");
        Patient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        titre1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titre1.setText("Date :");

        titre2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titre2.setText("Sexe:");

        Nom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nom.setText("...........................................");

        Ne.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ne.setText("................");

        Sexe_p.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sexe_p.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sexe_p.setText("................");

        SD.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        SD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(SD);

        AT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        AT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(AT);

        Patient1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient1.setText("ATCD");

        Patient2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient2.setText("Histoire de la maladie");

        HiM.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        HiM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(HiM);

        Patient3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient3.setText("Complement d'anamnese");

        CMa.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        CMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(CMa);

        Patient4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient4.setText("Examen Physique");

        ExP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ExP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(ExP);

        Patient5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient5.setText("Diagnostique");

        Diag.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Diag.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(Diag);

        Date_consul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Date_consul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Date_consul.setText("Date");

        Utilisateur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Utilisateur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Utilisateur.setText("User");

        Patient8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Patient8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient8.setText("Symtome dominant");

        javax.swing.GroupLayout imprimerLayout = new javax.swing.GroupLayout(imprimer);
        imprimer.setLayout(imprimerLayout);
        imprimerLayout.setHorizontalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addComponent(titre2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sexe_p, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addComponent(titre1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ne, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(316, 316, 316))))
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)
                            .addGroup(imprimerLayout.createSequentialGroup()
                                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Patient1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Patient2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Patient3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Patient4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Patient5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Patient8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_consul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Utilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(imprimerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        imprimerLayout.setVerticalGroup(
            imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre)
                    .addComponent(Nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre1)
                    .addComponent(Ne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre2)
                    .addComponent(Sexe_p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Patient8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Patient1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Patient3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Patient4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Patient5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Date_consul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Print.png"))); // NOI18N
        jMenuItem2.setText("Imprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_usradd.png"))); // NOI18N
        jMenuItem3.setText("Nom Client");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/Exit2.png"))); // NOI18N
        jMenuItem1.setText("Fermer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MPanelPrinter p=new MPanelPrinter(imprimer,1);
        p.setLRMargins(100);
        p.setTBMargins(90);
        p.print();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
        //String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
        //patient1= nom+"-"+post_nom;
        //Patient.setText("Patient : "+patient1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        //String nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
        //String post_nom = JOptionPane.showInputDialog(null, "Veuillez Saisire le Post Nom du client", "Facturation", JOptionPane.QUESTION_MESSAGE);
        //patient1= nom+"-"+post_nom;
        //Patient.setText("Patient : "+patient1);
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impression().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AT;
    private javax.swing.JTextPane CMa;
    private javax.swing.JLabel Date_consul;
    private javax.swing.JTextPane Diag;
    private javax.swing.JTextPane ExP;
    private javax.swing.JTextPane HiM;
    private javax.swing.JLabel Ne;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel Patient;
    private javax.swing.JLabel Patient1;
    private javax.swing.JLabel Patient2;
    private javax.swing.JLabel Patient3;
    private javax.swing.JLabel Patient4;
    private javax.swing.JLabel Patient5;
    private javax.swing.JLabel Patient8;
    private javax.swing.JTextPane SD;
    private javax.swing.JLabel Sexe_p;
    private javax.swing.JLabel Utilisateur;
    private javax.swing.JPanel imprimer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel titre1;
    private javax.swing.JLabel titre2;
    // End of variables declaration//GEN-END:variables

    void info_Patient(String Nomp, String Postnom, String Prenom, String date, String Sexe) {
        Nom_Pat=Nomp;
        Postnom_Pat=Postnom;
        Prenom_Pat=Prenom;
        Sexe_Pat=Sexe;
        Date_ne=date;
        Nom.setText(Nom_Pat+"-"+Postnom_Pat+" "+Prenom_Pat);
        Ne.setText(Date_ne);
        Sexe_p.setText(Sexe_Pat);
        
    }

    void info_Cons(String S_p, String ATCD_p, String HMA_p, String CA_p, String EP_p, String A_p, String Date) {
        s=S_p;
        ATCD=ATCD_p;
        HMA=HMA_p;
        CA=CA_p;
        EP=EP_p;
        A=A_p;
        Date_cons=Date;
        SD.setText(s);
        AT.setText(ATCD);
        HiM.setText(HMA);
        CMa.setText(CA);
        ExP.setText(EP);
        Diag.setText(A);
        Date_consul.setText(Date_cons);
    }

    void User(String User) {
        Use=User;
        Utilisateur.setText(Use);
    }
}
