/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Patient.java
 *
 * Created on 8 août 2018, 20:46:13
 */
package Medecin;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samy-MBIYA
 */
public class Liste_Patient extends javax.swing.JFrame {

    /** Creates new form Liste_Patient */
    public String id_p,nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em;
    public String user1,Id_pr1,tx1,tx2,tx3;
    private Statement state;
    private ResultSet result;
    protected Enregistrement enregistrement= new Enregistrement(); 
    protected Modification modification=new Modification();
    protected Suppression suppression=new Suppression();
    protected Sv sv=new Sv();
    
    public Liste_Patient() {
        initComponents();
        aff();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tx1 = new javax.swing.JTextField();
        Bt_rech = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tx2 = new javax.swing.JTextField();
        Tx3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bt_rech1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_liste = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        User_nam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Fichier = new javax.swing.JMenu();
        Rapport_Zone_de_sante = new javax.swing.JMenuItem();
        Editer = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Recherche Patient"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Tx1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx1ActionPerformed(evt);
            }
        });

        Bt_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_rech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_search.png"))); // NOI18N
        Bt_rech.setText("Recherche ");
        Bt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rechActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Numéro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nom");

        Tx2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx2ActionPerformed(evt);
            }
        });

        Tx3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Post Nom");

        Bt_rech1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_rech1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_tipp.png"))); // NOI18N
        Bt_rech1.setText("Actoiliser");
        Bt_rech1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rech1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Tx3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(Tx1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(Tx2))))
                .addGap(339, 339, 339)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_rech1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bt_rech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_rech1))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Tb_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Fiche", "Nom", "Postnom", "Prenom", "Sexe", "Date", "EC", "AD", "PH", "Pr", "Em"
            }
        ));
        Tb_liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_listeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_liste);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("   Docteur :");

        User_nam.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        User_nam.setText("user");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(User_nam))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Fichier.setText("File");

        Rapport_Zone_de_sante.setText("Rapport Zone de Santé");
        Rapport_Zone_de_sante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rapport_Zone_de_santeActionPerformed(evt);
            }
        });
        Fichier.add(Rapport_Zone_de_sante);

        jMenuBar1.add(Fichier);

        Editer.setText("Edit");
        jMenuBar1.add(Editer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    public void user(String Id_pr, String user)
    {
        user1=user;
        Id_pr1=Id_pr;
        User_nam.setText(user);
        
    }
    public void aff()//Affichage de 10 Dernier consultation
    {
        try {
            state = (Statement) connection.getInstance().createStatement();
            result = state.executeQuery("SELECT * FROM patient, sv WHERE patient.id_pa= SV.Id_pa ORDER BY Id_sv DESC LIMIT 0,25;");
            DefaultTableModel Table=  (DefaultTableModel) Tb_liste.getModel();
            String no;
            Table.setColumnCount(0);

                   Table.addColumn("id_pa");
                   Table.addColumn("Nom");
                   Table.addColumn("Post_nom");
                   Table.addColumn("Prenom");
                   Table.addColumn("Sexe");
                   Table.addColumn("DN");
                   Table.addColumn("EC");
                   Table.addColumn("Adresse");
                   Table.addColumn("Phone");
                   Table.addColumn("Profession");
                   Table.addColumn("Employeur");
                   Table.addColumn("ATCD");
                   Table.setRowCount(0);
            while (result.next())
                      {//
                          /*no=result.getString("Nom");
                          System.out.println(no);*/
                          Object[] objets= new Object[12];
                            objets[0]= result.getString("id_pa");
                            objets[1]= result.getString("Nom");
                            objets[2]= result.getString("Post_nom");
                            objets[3]= result.getString("Prenom");
                            objets[4]= result.getString("Sexe");
                            objets[5]= result.getString("DN");
                            objets[6]= result.getString("EC");
                            objets[7]= result.getString("Adresse");
                            objets[8]= result.getString("Phone");
                            objets[9]= result.getString("Profession");
                            objets[10]= result.getString("Employeur");
                            objets[11]= result.getString("ATCD");
                           Table.addRow(objets);
                      }
        } catch (SQLException ex) {
            Logger.getLogger(Liste_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
private void Tx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Tx1ActionPerformed

private void Bt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rechActionPerformed
// TODO add your handling code here:
        tx1=Tx1.getText();
        tx2=Tx2.getText();
        tx3=Tx3.getText();
        //postnom=Tx2.getText();    
    try {
            state = (Statement) connection.getInstance().createStatement();
            if ("".equals(tx1)){
                result = state.executeQuery("SELECT* FROM  patient WHERE Nom LIKE '"+"%"+tx2+"' OR Post_nom LIKE '"+"%"+tx3+"' ;");
            }
            else{
                result = state.executeQuery("SELECT* FROM  patient WHERE id_pa='"+tx1+"' ;");
            }
            Tx1.setText("");
            Tx2.setText("");
            Tx3.setText("");
            DefaultTableModel Table=(DefaultTableModel) Tb_liste.getModel();
            String no;
            Table.setColumnCount(0);

                   Table.addColumn("id_pa");
                   Table.addColumn("Nom");
                   Table.addColumn("Post_nom");
                   Table.addColumn("Prenom");
                   Table.addColumn("Sexe");
                   Table.addColumn("DN");
                   Table.addColumn("EC");
                   Table.addColumn("Adresse");
                   Table.addColumn("Phone");
                   Table.addColumn("Profession");
                   Table.addColumn("Employeur");
                   Table.addColumn("ATCD");
                   Table.setRowCount(0);
            while (result.next())
                      {//
                          /*no=result.getString("Nom");
                          System.out.println(no);*/
                          Object[] objets= new Object[12];
                            objets[0]= result.getString("id_pa");
                            objets[1]= result.getString("Nom");
                            objets[2]= result.getString("Post_nom");
                            objets[3]= result.getString("Prenom");
                            objets[4]= result.getString("Sexe");
                            objets[5]= result.getString("DN");
                            objets[6]= result.getString("EC");
                            objets[7]= result.getString("Adresse");
                            objets[8]= result.getString("Phone");
                            objets[9]= result.getString("Profession");
                            objets[10]= result.getString("Employeur");
                            objets[11]= result.getString("ATCD");
                           Table.addRow(objets);
                      }
        } catch (SQLException ex) {
            Logger.getLogger(Liste_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    
        // la vaveur du champ n'est pas null
        for(int i=0; i<Tb_liste.getRowCount(); i++) // compteur par rapport au tableau
        {   
            String nom_tri, pnom_tri;
            nom_tri=(String) Tb_liste.getModel().getValueAt(i, 1);// affecte la valeur de la celuile
            pnom_tri=(String)Tb_liste.getModel().getValueAt(i, 2);
            if( (nom == null ? nom_tri == null : nom.equals(nom_tri)) ||(postnom == null ? pnom_tri == null : postnom.equals(pnom_tri)) )
            {
                Tb_liste.changeSelection(i, 1, false, false);
                //System.out.println(nom_tri+"-"+pnom_tri);
            }else{
                
            }
        }    

}//GEN-LAST:event_Bt_rechActionPerformed


private void Tb_listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_listeMouseClicked
// TODO add your handling code here:
   int ligne_select= Tb_liste.getSelectedRowCount();//Nombre de lignes selectionner
   int in= Tb_liste.getSelectedRow();
   
    /*if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{*/
        if(ligne_select==1)
        {
            id_p=(String)Tb_liste.getModel().getValueAt(in, 0);
            nom=(String) Tb_liste.getModel().getValueAt(in, 1);
            postnom=(String) Tb_liste.getModel().getValueAt(in, 2);
            prenom=(String) Tb_liste.getModel().getValueAt(in, 3);
            sexe=(String) Tb_liste.getModel().getValueAt(in, 4);
            dn=(String) Tb_liste.getModel().getValueAt(in, 5);
            ec=(String) Tb_liste.getModel().getValueAt(in, 6);
            ad=(String) Tb_liste.getModel().getValueAt(in, 7);
            ph=(String) Tb_liste.getModel().getValueAt(in, 8);
            pr=(String) Tb_liste.getModel().getValueAt(in, 9);
            em=(String) Tb_liste.getModel().getValueAt(in, 10);
            String ATCD_p= (String) Tb_liste.getModel().getValueAt(in, 11);
            sv.info_patient(Id_pr1,user1,id_p, nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em,ATCD_p);
            Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
            int H=tailleEcran.height;
            int L=tailleEcran.width;
            H=H-1;
            L=L-1;
            sv.setSize(L, H);//Longeure et Hauteur l'ecran
            sv.setVisible(true);
            this.setVisible(false);
    }
   //}
   
}//GEN-LAST:event_Tb_listeMouseClicked

private void Tx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Tx2ActionPerformed

private void Tx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Tx3ActionPerformed

private void Bt_rech1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rech1ActionPerformed
// TODO add your handling code here:
    aff();
    
    //Liste_Patient();
}//GEN-LAST:event_Bt_rech1ActionPerformed

private void Rapport_Zone_de_santeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rapport_Zone_de_santeActionPerformed
// TODO add your handling code here:
   Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
    int H=tailleEcran.height;
    int L=tailleEcran.width;
    Rapport_zone_de_sante lp= new Rapport_zone_de_sante();
    lp.setSize(L, H);//Longeure et Hauteur l'ecran Id_pr1, dig, user1
    lp.user(Id_pr1, user1);
    lp.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_Rapport_Zone_de_santeActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Liste_Patient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_rech;
    private javax.swing.JButton Bt_rech1;
    private javax.swing.JMenu Editer;
    private javax.swing.JMenu Fichier;
    private javax.swing.JMenuItem Rapport_Zone_de_sante;
    private javax.swing.JTable Tb_liste;
    private javax.swing.JTextField Tx1;
    private javax.swing.JTextField Tx2;
    private javax.swing.JTextField Tx3;
    private javax.swing.JLabel User_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
