/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Liste_Patient.java
 *
 * Created on 8 août 2018, 20:46:13
 */
package Medecin;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samy-MBIYA
 */
public class Rapport_zone_de_sante extends javax.swing.JFrame {

    /** Creates new form Liste_Patient */
    public String id_p,nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em;
    public String user1,Id_pr1,tx1,tx2,tx3;
    private Statement state;
    private ResultSet result;
    protected Enregistrement enregistrement= new Enregistrement(); 
    protected Modification modification=new Modification();
    protected Suppression suppression=new Suppression();
    protected Sv sv=new Sv();
    
    public Rapport_zone_de_sante() {
        initComponents();
        aff();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Date = new javax.swing.JTextField();
        Bt_rech = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Periode2 = new javax.swing.JTextField();
        Periode1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bt_rech1 = new javax.swing.JButton();
        Mois = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_liste = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        User_nam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Recherche du Rapport"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Date.setFont(new java.awt.Font("Tahoma", 0, 14));
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Bt_rech.setFont(new java.awt.Font("Tahoma", 0, 14));
        Bt_rech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_search.png"))); // NOI18N
        Bt_rech.setText("Recherche ");
        Bt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rechActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Date  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Mois  : ");

        Periode2.setFont(new java.awt.Font("Tahoma", 0, 14));
        Periode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Periode2ActionPerformed(evt);
            }
        });

        Periode1.setFont(new java.awt.Font("Tahoma", 0, 14));
        Periode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Periode1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Periode : ");

        Bt_rech1.setFont(new java.awt.Font("Tahoma", 0, 14));
        Bt_rech1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packImages/b_tipp.png"))); // NOI18N
        Bt_rech1.setText("Actoiliser");
        Bt_rech1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rech1ActionPerformed(evt);
            }
        });

        Mois.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Mois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mois", "Janvier", "Fevrier", "Mars", "Avril", "Mais", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Periode1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(10, 10, 10)
                            .addComponent(Mois, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_rech1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Periode2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Bt_rech)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Bt_rech1))
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Periode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Periode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Tb_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Nom", "Post_Nom", "Pre Nom", "Sexe", "Symptomes Dominant", "Diagnostique", "Traitement"
            }
        ));
        Tb_liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_listeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_liste);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setText("   Docteur :");

        User_nam.setFont(new java.awt.Font("Tahoma", 3, 14));
        User_nam.setText("user");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(User_nam))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    public void user(String Id_pr, String user)
    {
        user1=user;
        Id_pr1=Id_pr;
        User_nam.setText(user);
        
    }
    public void aff()//Affichage de 10 Dernier consultation
    {
        try {
            state = (Statement) connection.getInstance().createStatement();
            result = state.executeQuery("SELECT consultation.Id_consultation,consultation.Date, patient.Nom,patient.Post_nom,patient.Prenom, patient.Sexe,consultation.s, consultation.A, traitement.Medicament FROM consultation,patient, traitement WHERE consultation.Id_pa=patient.id_pa AND consultation.Id_consultation=traitement.Id_cons AND patient.id_pa=traitement.Id_pa   ORDER BY consultation.Id_consultation DESC LIMIT 0,30");
            DefaultTableModel Table=  (DefaultTableModel) Tb_liste.getModel();
            String no;
            Table.setColumnCount(0);

                   Table.addColumn("ID");
                   Table.addColumn("Date");
                   Table.addColumn("Nom");
                   Table.addColumn("Post_nom");
                   Table.addColumn("Prenom");
                   Table.addColumn("Sexe");
                   Table.addColumn("Symptomes Dominant");
                   Table.addColumn("Diagnostique");
                   Table.addColumn("Traitement");
                   Table.setRowCount(0);
            while (result.next())
                      {//
                          /*no=result.getString("Nom");
                          System.out.println(no);*/
                          Object[] objets= new Object[9];
                            objets[0]= result.getString("Id_consultation");
                            objets[1]= result.getString("Date");
                            objets[2]= result.getString("Nom");
                            objets[3]= result.getString("Post_nom");
                            objets[4]= result.getString("Prenom");
                            objets[5]= result.getString("Sexe");
                            objets[6]= result.getString("s");
                            objets[7]= result.getString("A");
                            objets[8]= result.getString("Medicament");
                            Table.addRow(objets);
                      }
        } catch (SQLException ex) {
            Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DateActionPerformed

private void Bt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rechActionPerformed
// TODO add your handling code here:
tx2=Mois.getSelectedItem().toString();
tx1=Date.getText();
tx3=Periode1.getText();
    try {
            state = (Statement) connection.getInstance().createStatement();
            if ("".equals(tx3) || "Mois".equals(tx2) ){
                result = state.executeQuery(
                            "SELECT consultation.Id_consultation,consultation.Date, patient.Nom,patient.Post_nom,patient.Prenom, patient.Sexe,consultation.s, consultation.A, traitement.Medicament "
                            + "FROM consultation,patient, traitement "
                            + "WHERE consultation.Id_pa=patient.id_pa AND consultation.Id_consultation=traitement.Id_cons AND patient.id_pa=traitement.Id_pa  AND consultation.Date='"+Date.getText()+ "' ORDER BY consultation.Id_consultation DESC LIMIT 0,30");
            }
            else if("".equals(tx3) || "Mois".equals(tx1)){
                result = state.executeQuery("SELECT consultation.Id_consultation,consultation.Date, patient.Nom,patient.Post_nom,patient.Prenom, patient.Sexe,consultation.s, consultation.A, traitement.Medicament "
                            + "FROM consultation,patient, traitement "
                            + "WHERE consultation.Id_pa=patient.id_pa AND consultation.Id_consultation=traitement.Id_cons AND patient.id_pa=traitement.Id_pa  AND consultation.Date='"+tx2+ "' ORDER BY consultation.Id_consultation DESC LIMIT 0,30");
            }
            //Date.setText("");
            //Periode2.setText("");
            //Periode1.setText("");
            DefaultTableModel Table=(DefaultTableModel) Tb_liste.getModel();
            String no;
            Table.setColumnCount(0);

                   Table.addColumn("id_pa");
                   Table.addColumn("Nom");
                   Table.addColumn("Post_nom");
                   Table.addColumn("Prenom");
                   Table.addColumn("Sexe");
                   Table.addColumn("DN");
                   Table.addColumn("EC");
                   Table.addColumn("Adresse");
                   Table.addColumn("Phone");
                   Table.addColumn("Profession");
                   Table.addColumn("Employeur");
                   Table.addColumn("ATCD");
                   Table.setRowCount(0);
            while (result.next())
                      {//
                          /*no=result.getString("Nom");
                          System.out.println(no);*/
                          Object[] objets= new Object[12];
                            objets[0]= result.getString("id_pa");
                            objets[1]= result.getString("Nom");
                            objets[2]= result.getString("Post_nom");
                            objets[3]= result.getString("Prenom");
                            objets[4]= result.getString("Sexe");
                            objets[5]= result.getString("DN");
                            objets[6]= result.getString("EC");
                            objets[7]= result.getString("Adresse");
                            objets[8]= result.getString("Phone");
                            objets[9]= result.getString("Profession");
                            objets[10]= result.getString("Employeur");
                            objets[11]= result.getString("ATCD");
                           Table.addRow(objets);
                      }
        } catch (SQLException ex) {
            Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    
        // la vaveur du champ n'est pas null
        for(int i=0; i<Tb_liste.getRowCount(); i++) // compteur par rapport au tableau
        {   
            String nom_tri, pnom_tri;
            nom_tri=(String) Tb_liste.getModel().getValueAt(i, 1);// affecte la valeur de la celuile
            pnom_tri=(String)Tb_liste.getModel().getValueAt(i, 2);
            if( (nom == null ? nom_tri == null : nom.equals(nom_tri)) ||(postnom == null ? pnom_tri == null : postnom.equals(pnom_tri)) )
            {
                Tb_liste.changeSelection(i, 1, false, false);
                //System.out.println(nom_tri+"-"+pnom_tri);
            }else{
                
            }
        }    

}//GEN-LAST:event_Bt_rechActionPerformed


private void Tb_listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_listeMouseClicked
// TODO add your handling code here:
   int ligne_select= Tb_liste.getSelectedRowCount();//Nombre de lignes selectionner
   int in= Tb_liste.getSelectedRow();
   
    /*if( "".equals(nom)||"".equals(postnom))
    {
        JOptionPane.showMessageDialog(null, "Champs vide", "Erreur", JOptionPane.WARNING_MESSAGE);
    }else{*/
        if(ligne_select==1)
        {
            id_p=(String)Tb_liste.getModel().getValueAt(in, 0);
            nom=(String) Tb_liste.getModel().getValueAt(in, 1);
            postnom=(String) Tb_liste.getModel().getValueAt(in, 2);
            prenom=(String) Tb_liste.getModel().getValueAt(in, 3);
            sexe=(String) Tb_liste.getModel().getValueAt(in, 4);
            dn=(String) Tb_liste.getModel().getValueAt(in, 5);
            ec=(String) Tb_liste.getModel().getValueAt(in, 6);
            ad=(String) Tb_liste.getModel().getValueAt(in, 7);
            ph=(String) Tb_liste.getModel().getValueAt(in, 8);
            pr=(String) Tb_liste.getModel().getValueAt(in, 9);
            em=(String) Tb_liste.getModel().getValueAt(in, 10);
            String ATCD_p= (String) Tb_liste.getModel().getValueAt(in, 11);
            sv.info_patient(Id_pr1,user1,id_p, nom, postnom, prenom, sexe, dn, ec, ad, ph, pr, em,ATCD_p);
            Dimension tailleEcran= Toolkit.getDefaultToolkit().getScreenSize();// Recuperation de la taille de l'ecran
            int H=tailleEcran.height;
            int L=tailleEcran.width;
            sv.setSize(L, H);//Longeure et Hauteur l'ecran
            sv.setVisible(true);
            this.setVisible(false);
    }
   //}
   
}//GEN-LAST:event_Tb_listeMouseClicked

private void Periode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Periode2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Periode2ActionPerformed

private void Periode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Periode1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Periode1ActionPerformed

private void Bt_rech1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rech1ActionPerformed
// TODO add your handling code here:
    aff();
    
    //Liste_Patient();
}//GEN-LAST:event_Bt_rech1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rapport_zone_de_sante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Rapport_zone_de_sante().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_rech;
    private javax.swing.JButton Bt_rech1;
    private javax.swing.JTextField Date;
    private javax.swing.JComboBox Mois;
    private javax.swing.JTextField Periode1;
    private javax.swing.JTextField Periode2;
    private javax.swing.JTable Tb_liste;
    private javax.swing.JLabel User_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
